(function(){
const T={
en:{name:'English',dir:'ltr',brand:'SkillBridge',badge:'Europe • route engine MVP',eyebrow:'WORK ACROSS BORDERS — WITHOUT GUESSING',hero:'Can you really work in another European country?',lead:'SkillBridge combines',build:'Build your route',nat:'Nationality',res:'Current residence',qual:'Qualification country',job:'Profession',exp:'Experience',to:'Target country',lang:'Language level',stat:'Legal status',show:'Show my route →',free:'Free screening • official-source based • not legal advice',gap:'THE PRODUCT GAP',notjob:'Not another job board',things:'THE THINGS PEOPLE MISS',useful:'Useful checks before you move',trust:'Trust rule',official:'Open official source ↗',review:'Official/authoritative source • reviewed 2026',work:'Work rights',recognition:'Recognition',language:'Language',documents:'Documents',screen:'ROUTE SCREENING',workrights:'WORK RIGHTS',qualification:'QUALIFICATION',next:'YOUR NEXT ROUTE',ready:'DOCUMENT READINESS',why:'WHY THIS RESULT',verify:'Needs verification',caution:'Exact requirements vary by profession, country and status.'},
ar:{name:'العربية',dir:'rtl',brand:'SkillBridge',badge:'أوروبا • محرك المسار التجريبي',eyebrow:'اعمل عبر الحدود — بدون تخمين',hero:'هل يمكنك فعلاً العمل في دولة أوروبية أخرى؟',lead:'يجمع SkillBridge',build:'أنشئ مسارك',nat:'الجنسية',res:'الإقامة الحالية',qual:'دولة المؤهل',job:'المهنة',exp:'الخبرة',to:'الدولة المستهدفة',lang:'مستوى اللغة',stat:'الوضع القانوني',show:'اعرض مساري ←',free:'فحص مجاني • مبني على مصادر رسمية • ليس استشارة قانونية',gap:'فجوة المنتج',notjob:'لسنا موقع وظائف آخر',things:'أشياء يغفل عنها الناس',useful:'فحوصات مفيدة قبل الانتقال',trust:'قاعدة الثقة',official:'فتح المصدر الرسمي ↗',review:'مصدر رسمي/موثوق • تمت المراجعة 2026',work:'حق العمل',recognition:'الاعتراف بالمؤهل',language:'اللغة',documents:'الوثائق',screen:'فحص المسار',workrights:'حقوق العمل',qualification:'المؤهل',next:'خطوتك التالية',ready:'جاهزية الوثائق',why:'لماذا ظهرت هذه النتيجة',verify:'تحتاج إلى تحقق',caution:'تختلف المتطلبات الدقيقة حسب المهنة والدولة والوضع القانوني.'},
tr:{name:'Türkçe',dir:'ltr',brand:'SkillBridge',badge:'Avrupa • rota motoru MVP',eyebrow:'SINIRLAR ARASINDA ÇALIŞIN — TAHMİN ETMEDEN',hero:'Başka bir Avrupa ülkesinde gerçekten çalışabilir misiniz?',lead:'SkillBridge şunları birleştirir',build:'Rotanı oluştur',nat:'Uyruk',res:'Mevcut ikamet',qual:'Diploma/mesleki yeterlilik ülkesi',job:'Meslek',exp:'Deneyim',to:'Hedef ülke',lang:'Dil seviyesi',stat:'Hukuki durum',show:'Rotamı göster →',free:'Ücretsiz ön değerlendirme • resmi kaynaklara dayalı • hukuki danışmanlık değildir',gap:'ÜRÜNDEKİ BOŞLUK',notjob:'Sıradan bir iş ilanı sitesi değil',things:'İNSANLARIN GÖZDEN KAÇIRDIĞI ŞEYLER',useful:'Taşınmadan önce yararlı kontroller',trust:'Güven kuralı',official:'Resmi kaynağı aç ↗',review:'Resmi/güvenilir kaynak • 2026 incelendi',work:'Çalışma hakkı',recognition:'Mesleki tanıma',language:'Dil',documents:'Belgeler',screen:'ROTA TARAMASI',workrights:'ÇALIŞMA HAKLARI',qualification:'YETERLİLİK',next:'SONRAKİ ADIMIN',ready:'BELGE HAZIRLIĞI',why:'BU SONUÇ NEDENİ',verify:'Doğrulama gerekli',caution:'Kesin şartlar mesleğe, ülkeye ve statüye göre değişir.'},
de:{name:'Deutsch',dir:'ltr',brand:'SkillBridge',badge:'Europa • Routen-Engine MVP',eyebrow:'GRENZÜBERSCHREITEND ARBEITEN — OHNE RATEN',hero:'Kannst du wirklich in einem anderen europäischen Land arbeiten?',lead:'SkillBridge kombiniert',build:'Route erstellen',nat:'Staatsangehörigkeit',res:'Aktueller Wohnsitz',qual:'Land des Abschlusses',job:'Beruf',exp:'Erfahrung',to:'Zielland',lang:'Sprachniveau',stat:'Rechtlicher Status',show:'Meine Route anzeigen →',free:'Kostenlose Prüfung • auf offiziellen Quellen basierend • keine Rechtsberatung',gap:'DIE PRODUKTLÜCKE',notjob:'Keine weitere Jobbörse',things:'DINGE, DIE MENSCHEN ÜBERSEHEN',useful:'Nützliche Prüfungen vor dem Umzug',trust:'Vertrauensregel',official:'Offizielle Quelle öffnen ↗',review:'Offizielle/verlässliche Quelle • geprüft 2026',work:'Arbeitsrecht',recognition:'Anerkennung',language:'Sprache',documents:'Dokumente',screen:'ROUTENPRÜFUNG',workrights:'ARBEITSRECHT',qualification:'QUALIFIKATION',next:'DEIN NÄCHSTER WEG',ready:'DOKUMENTENVORBEREITUNG',why:'WARUM DIESES ERGEBNIS',verify:'Überprüfung erforderlich',caution:'Die genauen Anforderungen hängen von Beruf, Land und Status ab.'},
fr:{name:'Français',dir:'ltr',brand:'SkillBridge',badge:'Europe • moteur de parcours MVP',eyebrow:'TRAVAILLER AU-DELÀ DES FRONTIÈRES — SANS DEVINER',hero:'Pouvez-vous vraiment travailler dans un autre pays européen ?',lead:'SkillBridge combine',build:'Construire votre parcours',nat:'Nationalité',res:'Résidence actuelle',qual:'Pays du diplôme',job:'Profession',exp:'Expérience',to:'Pays cible',lang:'Niveau de langue',stat:'Statut juridique',show:'Voir mon parcours →',free:'Vérification gratuite • sources officielles • pas un conseil juridique',gap:'LE MANQUE DU MARCHÉ',notjob:'Pas un autre site d’emploi',things:'CE QUE LES GENS OUBLIENT',useful:'Vérifications utiles avant de partir',trust:'Règle de confiance',official:'Ouvrir la source officielle ↗',review:'Source officielle/de référence • vérifiée 2026',work:'Droit au travail',recognition:'Reconnaissance',language:'Langue',documents:'Documents',screen:'VÉRIFICATION DU PARCOURS',workrights:'DROIT AU TRAVAIL',qualification:'QUALIFICATION',next:'VOTRE PROCHAINE ÉTAPE',ready:'PRÉPARATION DES DOCUMENTS',why:'POURQUOI CE RÉSULTAT',verify:'À vérifier',caution:'Les exigences exactes varient selon la profession, le pays et le statut.'},
nl:{name:'Nederlands',dir:'ltr',brand:'SkillBridge',badge:'Europa • route-engine MVP',eyebrow:'WERKEN OVER DE GRENS — ZONDER TE GISSEN',hero:'Kun je echt in een ander Europees land werken?',lead:'SkillBridge combineert',build:'Bouw je route',nat:'Nationaliteit',res:'Huidige verblijfplaats',qual:'Land van kwalificatie',job:'Beroep',exp:'Ervaring',to:'Doelland',lang:'Taalniveau',stat:'Juridische status',show:'Mijn route tonen →',free:'Gratis screening • op officiële bronnen gebaseerd • geen juridisch advies',gap:'HET PRODUCTGAT',notjob:'Geen gewone vacaturebank',things:'DINGEN DIE MENSEN MISSEN',useful:'Nuttige checks voor je verhuist',trust:'Vertrouwensregel',official:'Officiële bron openen ↗',review:'Officiële/gezaghebbende bron • gecontroleerd 2026',work:'Werkrecht',recognition:'Erkenning',language:'Taal',documents:'Documenten',screen:'ROUTECONTROLE',workrights:'WERKRECHT',qualification:'KWALIFICATIE',next:'JE VOLGENDE STAP',ready:'DOCUMENTVOORBEREIDING',why:'WAAROM DIT RESULTAAT',verify:'Verificatie nodig',caution:'De exacte eisen verschillen per beroep, land en status.'},
es:{name:'Español',dir:'ltr',brand:'SkillBridge',badge:'Europa • motor de rutas MVP',eyebrow:'TRABAJAR ENTRE FRONTERAS — SIN ADIVINAR',hero:'¿Realmente puedes trabajar en otro país europeo?',lead:'SkillBridge combina',build:'Construye tu ruta',nat:'Nacionalidad',res:'Residencia actual',qual:'País de la cualificación',job:'Profesión',exp:'Experiencia',to:'País de destino',lang:'Nivel de idioma',stat:'Situación legal',show:'Mostrar mi ruta →',free:'Evaluación gratuita • basada en fuentes oficiales • no es asesoramiento jurídico',gap:'LA BRECHA DEL PRODUCTO',notjob:'No es otra bolsa de trabajo',things:'LO QUE LA GENTE PASA POR ALTO',useful:'Comprobaciones útiles antes de mudarte',trust:'Regla de confianza',official:'Abrir fuente oficial ↗',review:'Fuente oficial/fiable • revisada 2026',work:'Derecho a trabajar',recognition:'Reconocimiento',language:'Idioma',documents:'Documentos',screen:'EVALUACIÓN DE RUTA',workrights:'DERECHO AL TRABAJO',qualification:'CUALIFICACIÓN',next:'TU PRÓXIMO PASO',ready:'PREPARACIÓN DE DOCUMENTOS',why:'POR QUÉ ESTE RESULTADO',verify:'Necesita verificación',caution:'Los requisitos exactos varían según la profesión, el país y la situación.'},
it:{name:'Italiano',dir:'ltr',brand:'SkillBridge',badge:'Europa • motore percorso MVP',eyebrow:'LAVORARE OLTRE CONFINE — SENZA INDOVINARE',hero:'Puoi davvero lavorare in un altro paese europeo?',lead:'SkillBridge combina',build:'Crea il tuo percorso',nat:'Nazionalità',res:'Residenza attuale',qual:'Paese della qualifica',job:'Professione',exp:'Esperienza',to:'Paese di destinazione',lang:'Livello linguistico',stat:'Stato giuridico',show:'Mostra il mio percorso →',free:'Controllo gratuito • basato su fonti ufficiali • non è consulenza legale',gap:'IL VUOTO DEL PRODOTTO',notjob:'Non è un altro portale di lavoro',things:'COSE CHE LE PERSONE NON CONSIDERANO',useful:'Controlli utili prima del trasferimento',trust:'Regola di fiducia',official:'Apri fonte ufficiale ↗',review:'Fonte ufficiale/autorevole • verificata 2026',work:'Diritto al lavoro',recognition:'Riconoscimento',language:'Lingua',documents:'Documenti',screen:'CONTROLLO DEL PERCORSO',workrights:'DIRITTO AL LAVORO',qualification:'QUALIFICA',next:'IL TUO PROSSIMO PASSO',ready:'PREPARAZIONE DOCUMENTI',why:'PERCHÉ QUESTO RISULTATO',verify:'Da verificare',caution:'I requisiti esatti variano in base a professione, paese e status.'},
pl:{name:'Polski',dir:'ltr',brand:'SkillBridge',badge:'Europa • silnik ścieżki MVP',eyebrow:'PRACA PONAD GRANICAMI — BEZ ZGADYWANIA',hero:'Czy naprawdę możesz pracować w innym kraju europejskim?',lead:'SkillBridge łączy',build:'Zbuduj swoją ścieżkę',nat:'Obywatelstwo',res:'Obecne miejsce pobytu',qual:'Kraj uzyskania kwalifikacji',job:'Zawód',exp:'Doświadczenie',to:'Kraj docelowy',lang:'Poziom języka',stat:'Status prawny',show:'Pokaż moją ścieżkę →',free:'Bezpłatne sprawdzenie • oparte na źródłach oficjalnych • nie jest poradą prawną',gap:'LUKA NA RYNKU',notjob:'To nie jest kolejna wyszukiwarka ofert',things:'RZECZY, KTÓRE LUDZIE PRZEOCZAJĄ',useful:'Przydatne kontrole przed przeprowadzką',trust:'Zasada zaufania',official:'Otwórz źródło oficjalne ↗',review:'Źródło oficjalne/wiarygodne • sprawdzone 2026',work:'Prawo do pracy',recognition:'Uznanie kwalifikacji',language:'Język',documents:'Dokumenty',screen:'SPRAWDZENIE ŚCIEŻKI',workrights:'PRAWO DO PRACY',qualification:'KWALIFIKACJE',next:'NASTĘPNY KROK',ready:'PRZYGOTOWANIE DOKUMENTÓW',why:'DLACZEGO TEN WYNIK',verify:'Wymaga weryfikacji',caution:'Dokładne wymagania zależą od zawodu, kraju i statusu.'},
ro:{name:'Română',dir:'ltr',brand:'SkillBridge',badge:'Europa • motor de traseu MVP',eyebrow:'MUNCĂ PESTE GRANIȚE — FĂRĂ GHICIT',hero:'Poți lucra cu adevărat într-o altă țară europeană?',lead:'SkillBridge combină',build:'Construiește-ți traseul',nat:'Naționalitate',res:'Reședința actuală',qual:'Țara calificării',job:'Profesie',exp:'Experiență',to:'Țara țintă',lang:'Nivel de limbă',stat:'Statut juridic',show:'Arată-mi traseul →',free:'Verificare gratuită • pe baza surselor oficiale • nu este consultanță juridică',gap:'LIPSA DIN PIAȚĂ',notjob:'Nu este încă un site de joburi',things:'LUCRURI PE CARE OAMENII LE OMIT',useful:'Verificări utile înainte de mutare',trust:'Regula încrederii',official:'Deschide sursa oficială ↗',review:'Sursă oficială/de încredere • verificată 2026',work:'Drept de muncă',recognition:'Recunoaștere',language:'Limbă',documents:'Documente',screen:'VERIFICAREA TRASEULUI',workrights:'DREPT DE MUNCĂ',qualification:'CALIFICARE',next:'URMĂTORUL PAS',ready:'PREGĂTIREA DOCUMENTELOR',why:'DE CE ACEST REZULTAT',verify:'Necesită verificare',caution:'Cerințele exacte diferă în funcție de profesie, țară și statut.'},
uk:{name:'Українська',dir:'ltr',brand:'SkillBridge',badge:'Європа • MVP маршруту',eyebrow:'ПРАЦЮЙТЕ ЧЕРЕЗ КОРДОНИ — БЕЗ ВГАДУВАННЯ',hero:'Чи справді ви можете працювати в іншій європейській країні?',lead:'SkillBridge поєднує',build:'Побудуйте свій маршрут',nat:'Громадянство',res:'Поточне проживання',qual:'Країна кваліфікації',job:'Професія',exp:'Досвід',to:'Цільова країна',lang:'Рівень мови',stat:'Правовий статус',show:'Показати мій маршрут →',free:'Безкоштовна перевірка • на основі офіційних джерел • не є юридичною консультацією',gap:'ПРОГАЛИНА ПРОДУКТУ',notjob:'Це не ще один сайт вакансій',things:'РЕЧІ, ЯКІ ЛЮДИ НЕ ВРАХОВУЮТЬ',useful:'Корисні перевірки перед переїздом',trust:'Правило довіри',official:'Відкрити офіційне джерело ↗',review:'Офіційне/надійне джерело • перевірено 2026',work:'Право на роботу',recognition:'Визнання',language:'Мова',documents:'Документи',screen:'ПЕРЕВІРКА МАРШРУТУ',workrights:'ПРАВО НА РОБОТУ',qualification:'КВАЛІФІКАЦІЯ',next:'НАСТУПНИЙ КРОК',ready:'ПІДГОТОВКА ДОКУМЕНТІВ',why:'ЧОМУ ТАКИЙ РЕЗУЛЬТАТ',verify:'Потрібна перевірка',caution:'Точні вимоги залежать від професії, країни та статусу.'},
pt:{name:'Português',dir:'ltr',brand:'SkillBridge',badge:'Europa • motor de rotas MVP',eyebrow:'TRABALHE ATRAVÉS DAS FRONTEIRAS — SEM ADIVINHAR',hero:'Pode realmente trabalhar noutro país europeu?',lead:'O SkillBridge combina',build:'Crie o seu percurso',nat:'Nacionalidade',res:'Residência atual',qual:'País da qualificação',job:'Profissão',exp:'Experiência',to:'País de destino',lang:'Nível de idioma',stat:'Situação legal',show:'Mostrar o meu percurso →',free:'Verificação gratuita • baseada em fontes oficiais • não é aconselhamento jurídico',gap:'A LACUNA DO PRODUTO',notjob:'Não é mais um portal de emprego',things:'COISAS QUE AS PESSOAS ESQUECEM',useful:'Verificações úteis antes da mudança',trust:'Regra de confiança',official:'Abrir fonte oficial ↗',review:'Fonte oficial/confiável • revista em 2026',work:'Direito de trabalhar',recognition:'Reconhecimento',language:'Idioma',documents:'Documentos',screen:'VERIFICAÇÃO DO PERCURSO',workrights:'DIREITO AO TRABALHO',qualification:'QUALIFICAÇÃO',next:'PRÓXIMO PASSO',ready:'PREPARAÇÃO DE DOCUMENTOS',why:'PORQUE ESTE RESULTADO',verify:'Requer verificação',caution:'Os requisitos exatos variam consoante a profissão, o país e o estatuto.'}
};
const optionKeys={
'Turkey':{ar:'تركيا',tr:'Türkiye'},'Poland':{ar:'بولندا',pl:'Polska'},'Romania':{ar:'رومانيا',ro:'România'},'Ukraine':{ar:'أوكرانيا',uk:'Україна'},'Morocco':{ar:'المغرب',fr:'Maroc'},'Algeria':{ar:'الجزائر',fr:'Algérie'},'Tunisia':{ar:'تونس',fr:'Tunisie'},'Georgia':{ar:'جورجيا'},'Serbia':{ar:'صربيا'},'India':{ar:'الهند'},'United Kingdom':{ar:'المملكة المتحدة',fr:'Royaume-Uni',de:'Vereinigtes Königreich',es:'Reino Unido'},'Belgium':{ar:'بلجيكا',fr:'Belgique',de:'Belgien',nl:'België'},'Netherlands':{ar:'هولندا',fr:'Pays-Bas',de:'Niederlande',nl:'Nederland'},'Germany':{ar:'ألمانيا',fr:'Allemagne',de:'Deutschland',nl:'Duitsland'},'France':{ar:'فرنسا',fr:'France',de:'Frankreich'},'Austria':{ar:'النمسا',de:'Österreich'},'Sweden':{ar:'السويد',de:'Schweden'},'Denmark':{ar:'الدنمارك',de:'Dänemark'},'Ireland':{ar:'أيرلندا',de:'Irland'},'Italy':{ar:'إيطاليا',it:'Italia'},'Spain':{ar:'إسبانيا',es:'España'},'Portugal':{ar:'البرتغال',pt:'Portugal'},'Finland':{ar:'فنلندا'},'Norway':{ar:'النرويج'},'Switzerland':{ar:'سويسرا'},'Czechia':{ar:'التشيك'},'Hungary':{ar:'المجر'},'Greece':{ar:'اليونان'},'Croatia':{ar:'كرواتيا'},'Slovakia':{ar:'سلوفاكيا'},'Slovenia':{ar:'سلوفينيا'},'Lithuania':{ar:'ليتوانيا'},'Latvia':{ar:'لاتفيا'},'Estonia':{ar:'إستونيا'},'Luxembourg':{ar:'لوكسمبورغ'},'Bulgaria':{ar:'بلغاريا'},'Cyprus':{ar:'قبرص'},'Malta':{ar:'مالطا'},'Other / not listed':{ar:'أخرى / غير مدرجة'},
'Less than 1 year':{ar:'أقل من سنة'},'1–2 years':{ar:'1–2 سنة'},'3–4 years':{ar:'3–4 سنوات'},'5–9 years':{ar:'5–9 سنوات'},'10+ years':{ar:'10+ سنوات'},'None / just starting':{ar:'لا أعرف / بدأت للتو'},'Native / near-native':{ar:'لغة أم / قريب من مستوى المتحدث الأصلي'},'EU / EEA / Swiss citizen':{ar:'مواطن من الاتحاد الأوروبي / المنطقة الاقتصادية الأوروبية / سويسرا'},'Non-EU citizen — living outside the EU':{ar:'مواطن من خارج الاتحاد الأوروبي — يعيش خارج الاتحاد'},'Non-EU citizen — legally resident in an EU country':{ar:'مواطن من خارج الاتحاد الأوروبي — مقيم قانونيًا في دولة من الاتحاد'},'Not sure / another status':{ar:'غير متأكد / وضع آخر'}
};
const langs=Object.keys(T);
function trOption(v,l){return (optionKeys[v]&&optionKeys[v][l])||v}
function setStatic(l){const t=T[l]||T.en;document.documentElement.lang=l;document.documentElement.dir=t.dir;document.title='SkillBridge Europe';
 const qs=[['.badge','badge'],['.hero .eyebrow','eyebrow'],['.hero h1','hero'],['.hero .lead','lead'],['.card h2','build'],['.sec:nth-of-type(2) .eyebrow','gap'],['.sec:nth-of-type(2) h2','notjob'],['.sec:nth-of-type(3) .eyebrow','things'],['.sec:nth-of-type(3) h2','useful']];
 qs.forEach(([q,k])=>{const e=document.querySelector(q);if(e){if(k==='lead'){e.innerHTML=t.lead+' <b>nationality, residence, qualification country, profession, experience and language</b> to show the main route blockers and the next official checks.'}else e.textContent=t[k]||e.textContent}});
 const pills=document.querySelectorAll('.pills .pill');[t.work,t.recognition,t.language,t.documents].forEach((x,i)=>{if(pills[i])pills[i].textContent=x});
 const labels=document.querySelectorAll('.form label');const ks=['nat','res','qual','job','exp','to','lang','stat'];ks.forEach((k,i)=>{if(labels[i])labels[i].firstChild.nodeValue=(t[k]||k)+' '});
 const b=document.querySelector('.form+button');if(b)b.textContent=t.show;const tiny=document.querySelector('.tiny');if(tiny)tiny.textContent=t.free;
 const sect=document.querySelectorAll('.sec');if(sect[0]&&sect[0].id!=='result'){};
 const dark=document.querySelector('.dark');if(dark){const h=dark.querySelector('h3');if(h)h.textContent=t.trust}
 document.querySelectorAll('select').forEach(s=>Array.from(s.options).forEach(o=>o.textContent=trOption(o.value,l)));
 const sel=document.getElementById('sb-language');if(sel)sel.value=l;
 localStorage.setItem('sb_lang',l);
}
function addSelector(){const nav=document.querySelector('.nav');if(!nav||document.getElementById('sb-language'))return;const s=document.createElement('select');s.id='sb-language';s.title='Language';s.style.cssText='width:auto;margin:0 0 0 10px;padding:8px 28px 8px 9px;border-radius:9px;font-weight:800';langs.forEach(l=>s.add(new Option(T[l].name,l)));s.addEventListener('change',()=>setStatic(s.value));nav.appendChild(s)}
function boot(){addSelector();let l=localStorage.getItem('sb_lang')||'en';if(!T[l])l='en';setStatic(l);const r=document.getElementById('result');if(r){new MutationObserver(()=>{const t=T[l]||T.en;const map={'ROUTE SCREENING':t.screen,'WORK RIGHTS':t.workrights,'QUALIFICATION':t.qualification,'YOUR NEXT ROUTE':t.next,'DOCUMENT READINESS':t.ready,'WHY THIS RESULT':t.why,'Needs verification':t.verify};r.querySelectorAll('*').forEach(e=>{if(e.childElementCount===0&&map[e.textContent.trim()])e.textContent=map[e.textContent.trim()]})}).observe(r,{childList:true,subtree:true})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
